// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomepageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homepage() {
    driver.get("https://automationintesting.online/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > img")).click();
    driver.findElement(By.cssSelector(".content:nth-child(2) > img")).click();
    driver.findElement(By.cssSelector(".col-sm-3:nth-child(3) > img")).click();
    driver.findElement(By.linkText("restful-booker-platform source")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("sf");
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys("dgdg");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("1514@gmail.com");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("9265716416");
    driver.findElement(By.cssSelector(".btn:nth-child(6)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("sdf");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("1514@gmail.com");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("9265716416");
    driver.findElement(By.id("subject")).click();
    driver.findElement(By.id("subject")).sendKeys("hg");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("sfadsgsfdhdfjfdjdfjdjgj");
    driver.findElement(By.id("submitContact")).click();
    {
      WebElement element = driver.findElement(By.id("submitContact"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("sfadsgsfdhdfjfdjdfjdjgjdgshsfh");
    driver.findElement(By.id("submitContact")).click();
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("sfadsgsfdhdfjfdjdfjdjgjdgshsfhsedyshh");
    driver.findElement(By.id("submitContact")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("sdfdgsdgsdg");
    driver.findElement(By.id("submitContact")).click();
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("09265716416");
    driver.findElement(By.id("submitContact")).click();
    driver.findElement(By.id("subject")).click();
    driver.findElement(By.id("subject")).sendKeys("hgsdgfg");
    driver.findElement(By.id("submitContact")).click();
    driver.close();
  }
}
